### ISSUE TITLE
Join DataFrame on multiple columns

### ISSUE THREAD

**Issue by eric-liuyd** [nhl/dflib#135]
How to join two DataFrame objects on multiple common columns? I find `leftJoin().on()` can only take `String` arg but not `String...` arg. And the following code can only join on one column.

`DataFrame df = df1.leftJoin().on("col_a", "col_a").with(df2);`

**Comment by andrus** [comment]
Hi, you can provide `on` multiple times in the same join, each invocation defining separate join criterion.

**Comment by andrus** [comment]
Closing. I think the question is answered
