### ISSUE TITLE
Storing DataFrame in Excel

### ISSUE THREAD

**Issue by andrus** [nhl/dflib#138]
Already have ExcelLoader per #136. Let's also implemented ExcelSaver.

**Comment by chaojun-zhang** [comment]
Hi Andrus, do you have a time to look at the PR for this issue?

**Comment by andrus** [comment]
Hi @chaojun-zhang  . Thanks for your contribution. I will definitely find time to review it. 

Since this one is bigger than a simple bug fix, I'll need to ask you to sign and email us a Contributor License Agreement that we use for all ObjectStyle open source projects (DFLib, Bootique.io, Agrest.io) - https://www.objectstyle.com/f/cla/icla.pdf This is modeled after the CLA from the Apache Foundation and allows us to legally distribute DFLib and other projects under the Apache license. Once we have you CLA on file, we can accept this and any future contributions without any delays.

**Comment by andrus** [comment]
I just committed my own simple implementation. It would merge DataFrames to an existing Excel by sheet name (i.e. saved sheets are overridden, other sheets are preserved).

**Comment by andrus** [comment]
Added a few more options, such as custom per-column cell styles, column widths policies, etc.
