### ISSUE TITLE
Use Exp.getColumn instead of  Exp.toQL for method DataFrame.selectColumns

### ISSUE THREAD

**Issue by chaojun-zhang** [nhl/dflib#142]
I have a a unit test for AsExp as below:

```java
DataFrame city = DataFrame.newFrame("city").foldByRow(
        "beijing", "shanghai" ).selectColumns(Exp.$str("city").as("cityName"));

new DataFrameAsserts(city, "cityName")
        .expectHeight(2)
        .expectRow(0, "beijing")
        .expectRow(1, "shanghai");

```
and got unit test failed with error message below: 

org.opentest4j.AssertionFailedError: DataFrame columns differ from expected ==> array contents differ at index [0], expected: <cityName> but was: <city as cityName>
 
I would suggest to use Exp.getColumn instead of  Exp.toQL for method DataFram.selectColumns ?

If agreed, I would like to submit a PR to fix this ? 

PR: https://github.com/nhl/dflib/pull/143

**Comment by andrus** [comment]
Good catch. Definitely a bug. Here is the exception details:

```
org.opentest4j.AssertionFailedError: DataFrame columns differ from expected ==> array contents differ 
at index [1], expected: <c> but was: <a * a as c>
```
