### ISSUE TITLE
JsonLoader add columnType function

### ISSUE THREAD

**Issue by wangboshun** [nhl/dflib#178]
I don't find columnType   method  in JsonLoader
What can be replaced now? Except for  convertColumn function。

**Comment by andrus** [comment]
Yeah, there's somewhat intentional asymmetry with say CsvLoader. There's no particular performance benefit in defining type transformations inside the loader. The caller can easily transform types in the resulting DataFrame via `convertColumn` as you mentioned. Is this undesirable for any reason?

**Comment by andrus** [comment]
Thinking about this some more, I guess "convertColumn" is going to be more verbose than simply specifying a desired type. In the yet unreleased 0.16 there are functions like `Exp.castAsDate()`, `Exp.castAsInt()`, etc., that could help to solve it. But I guess I can see the value of "columnType" as well. Let me put it on my TODO

**Comment by wangboshun** [comment]
I think csv. excel. json and so on have a unified set of methods that specify types at build time, rather than converting types after build

**Comment by andrus** [comment]
So if we look at different loaders, some have a rich set of built-in data types (SqlLoader, AvroLoader), others - a minimal set (ExcelLoader, JsonLoader), and then there's CsvLoader that treats everything as a String. I suppose we can add converter methods to the second category.

**Comment by wangboshun** [comment]
Will it correspond to the panda method？

**Comment by wangboshun** [comment]
Developers using pandas can use dflib immediately

**Comment by andrus** [comment]
I will need to play with the API. At the minimum it will mirror the CsvLoader API, or will be some expression-based alternative.

**Comment by andrus** [comment]
Just added a bunch of methods to `CsvLoader` - `columnType`, `boolColumn`, `intColumn`, etc.
