### ISSUE TITLE
DFLib lack of "addRow" method

### ISSUE THREAD

**Issue by wangboshun** [nhl/dflib#193]
For example：
     df.addRow(index,column,val)

**Comment by wangboshun** [comment]
df.appendRow(column,val)

**Comment by wangboshun** [comment]
I do not look the hashmap convert row method,and List<hashmap> convert datarow method.

**Comment by wangboshun** [comment]
I do not look the hashmap convert to row method,and List<hashmap> convert to datarow method.

**Comment by wangboshun** [comment]
I do not look the hashmap convert to row method,and List convert to dataframe method.

**Comment by andrus** [comment]
Been thinking about adding this API. Considering the column nature of the DataFrame, it won't be particulary efficient, but I understand how it can be convenient. 

In the meantime, the way to expand a DataFrame verifically is using `vConcat` (i.e. creating another DataFrame with new rows, and concatentaing it with an existing one).

**Comment by andrus** [comment]
Just committed `DataFrame.addRow(Map<String, Object>)`. For all its convenience, note that it has a fairly bad performance. So if you need to add just one or two rows, feel free to use it. But if you are adding lots of rows, create another DataFrame from your data and use `vConcat`.
